name: 'Chatwork Messaging Action'
description: 'Send message to Chatwork.'
author: 'okuzawats'
branding:
  icon: 'message-square'
  color: 'red'
inputs:
  apiToken:
    required: true
    description: 'Chatwork API token'
  roomId:
    required: true
    description: 'Chatroom ID'
  message:
    required: true
    description: 'Message to send'
  taskUserId:
    required: false
    description: 'User in charge of task. '
runs:
  using: 'composite'
  steps:
    - name: checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
    - name: set up ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: '3.1.0'
    - run: ruby $GITHUB_ACTION_PATH/main.rb
      shell: sh
      env:
        API_TOKEN: ${{ inputs.apiToken }}
        ROOM_ID: ${{ inputs.roomId }}
        MESSAGE: ${{ inputs.message }}
        TASK_USER_ID: ${{ inputs.taskUserId }}
