name: 'Chatwork Messaging Action'
description: 'Send message to Chatwork.'
author: 'okuzawats'
branding:
  icon: 'message-square'
  color: 'red'
inputs:
  apiToken:
    required: true
    description: 'Chatwork API token'
  roomId:
    required: true
    description: 'Chatroom ID'
  messageType:
    description: 'Message type to send. default is message.'
    type: choice
    default: 'message'
    required: false
    options:
      - message
      - task
  message:
    required: true
    description: 'Message to send'
runs:
  using: 'composite'
  steps:
    - name: checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
    - name: set up ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: '3.1.0'
    - run: ruby $GITHUB_ACTION_PATH/main.rb
      shell: sh
      env:
        API_TOKEN: ${{ inputs.apiToken }}
        ROOM_ID: ${{ inputs.roomId }}
        MESSAGE: ${{ inputs.message }}
    - name: debug type
      run: echo type = ${{ inputs.messageType }}
